# Generated by Django 3.2.7 on 2021-09-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210912_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='Hospital_name',
            new_name='hospital_name',
        ),
    ]
